INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-APPETIZERS-VEG', 'Veg', 'CAT-APPETIZERS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-APPETIZERS-NON_VEG', 'Non Veg', 'CAT-APPETIZERS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-CURRIES-VEG', 'Veg', 'CAT-CURRIES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-NOODLES-NON_VEG', 'Non Veg', 'CAT-NOODLES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-NOODLES-VEG', 'Veg', 'CAT-NOODLES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BEVERAGES-FRESH_JUICE', 'Fresh Juice', 'CAT-BEVERAGES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-DESSERTS-PASTRY', 'Pastry', 'CAT-DESSERTS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-DESSERTS-ICECREAMS', 'Icecreams', 'CAT-DESSERTS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BEVERAGES-MILKSHAKES', 'Milkshakes', 'CAT-BEVERAGES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SOUPS-NON_VEG', 'Non Veg', 'CAT-SOUPS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SOUPS-VEG', 'Veg', 'CAT-SOUPS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SANDWICHES-NON_VEG', 'Non Veg', 'CAT-SANDWICHES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-PIZZAS-NON_VEG', 'Non Veg', 'CAT-PIZZAS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-APPETIZERS-BARBECUE', 'Barbecue', 'CAT-APPETIZERS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BEVERAGES-HOT', 'Hot', 'CAT-BEVERAGES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-MAIN_COURSE-BIRYANIS', 'Biryanis', 'CAT-MAIN_COURSE', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SANDWICHES-VEG', 'Veg', 'CAT-SANDWICHES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-MAIN_COURSE-INDIAN_BREADS', 'Indian Breads', 'CAT-MAIN_COURSE', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-CURRIES-NON_VEG', 'Non Veg', 'CAT-CURRIES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BEVERAGES-COLD', 'Cold', 'CAT-BEVERAGES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-MAIN_COURSE-RICE_VARIETIES', 'Rice Varieties', 'CAT-MAIN_COURSE', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-KICK_GRASS_SPECIALS-NON_VEG', 'Non Veg', 'CAT-KICK_GRASS_SPECIALS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-KICK_GRASS_SPECIALS-VEG', 'Veg', 'CAT-KICK_GRASS_SPECIALS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BURGERS-NON_VEG', 'Non Veg', 'CAT-BURGERS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-DOSAS-NON_VEG', 'Non Veg', 'CAT-DOSAS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-ROLLS-NON_VEG', 'Non Veg', 'CAT-ROLLS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-PASTAS-NON_VEG', 'Non Veg', 'CAT-PASTAS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SIZZLERS-NON_VEG', 'Non Veg', 'CAT-SIZZLERS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SIDES-SIDES', 'Sides', 'CAT-SIDES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SIDES-SALADS', 'Salads', 'CAT-SIDES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BURGERS-VEG', 'Veg', 'CAT-BURGERS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-BEVERAGES-MOJITOS', 'Mojitos', 'CAT-BEVERAGES', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-FRIED_RICE-NON_VEG', 'Non Veg', 'CAT-FRIED_RICE', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-FRIED_RICE-VEG', 'Veg', 'CAT-FRIED_RICE', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-DESSERTS-FRUITS', 'Fruits', 'CAT-DESSERTS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-DESSERTS-SWEETS', 'Sweets', 'CAT-DESSERTS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-DOSAS-VEG', 'Veg', 'CAT-DOSAS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-PIZZAS-VEG', 'Veg', 'CAT-PIZZAS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-ROLLS-VEG', 'Veg', 'CAT-ROLLS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-PASTAS-VEG', 'Veg', 'CAT-PASTAS', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SNACK-NON_VEG', 'Non Veg', 'CAT-SNACK', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SNACK-VEG', 'Veg', 'CAT-SNACK', 'BIZ-RES-0001');
INSERT INTO subcategories (id, name, category_id, business_id) VALUES ('SUBCAT-SIZZLERS-VEG', 'Veg', 'CAT-SIZZLERS', 'BIZ-RES-0001');