INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00001', '65 - Babycorn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00002', '65 - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00003', '65 - Egg', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00004', '65 - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00005', '65 - Gobi', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00006', '65 - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00007', '65 - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00008', '65 - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00009', 'Aloo Capsicum', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00010', 'Aloo Gobi Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00011', 'Aloo Jeera', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00012', 'Aloo Matar', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00013', 'Aloo Paneer Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00014', 'American Chopsey - Chicken', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00015', 'American Chopsey - Veg', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00016', 'Apple Juice', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00017', 'Apple Pie', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00018', 'Apple Pie with Icecream', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00019', 'Appuchi Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00020', 'Arabian Delight - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00021', 'Arabian Delight - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00022', 'Arabian Delight M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00023', 'Assorted Veg Platter', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00024', 'Authentic Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00025', 'Authentic Soup - Mutton', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00026', 'Authentic Soup - Tomato', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00027', 'Authentic Soup - Veg', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00028', 'Baked Vegetables', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00029', 'BBQ Chicken Grilled Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00030', 'BBQ Chicken Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00031', 'BBQ Chicken Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00032', 'BBQ Prawns with Roast Chilli Salsa', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00033', 'Bhurji - Egg', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00034', 'Bhurji - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00035', 'Bindi Kadai', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00036', 'Bindi Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00037', 'Black Coffee', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00038', 'Black Tea', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00039', 'Blackcurrent - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00040', 'Blackcurrent - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00041', 'Blackcurrent M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00042', 'Boiled Egg - 2 Pieces', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00043', 'Bone Chicken Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00044', 'Bread Butter Jam Toast', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00045', 'Bread Omlette', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00046', 'Breads - Aloo Kulcha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00047', 'Breads - Aloo Paratha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00048', 'Breads - Butter Kulcha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00049', 'Breads - Butter Naan', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00050', 'Breads - Butter Roti', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00051', 'Breads - Garlic Naan', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00052', 'Breads - Gobi Paratha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00053', 'Breads - Kulcha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00054', 'Breads - Naan', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00055', 'Breads - Paneer Kulcha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00056', 'Breads - Paneer Paratha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00057', 'Breads - Tandoori Roti', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00058', 'Brownie', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00059', 'Brownie Sizzlers', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00060', 'Brownie with Icecream', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00061', 'Bruschetta', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00062', 'Butter Chicken Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00063', 'Buttermilk', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00064', 'Butterscotch - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00065', 'Butterscotch - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00066', 'Butterscotch M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00067', 'Caramel Blast', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00068', 'Caribbean Chicken', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00069', 'Cashew Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00070', 'Channa Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00071', 'Chapati', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00072', 'Cheese Garlic Bread', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00073', 'Chef''s Delight Atta Roll - Chicken', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00074', 'Chef''s Delight Atta Roll - Veg', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00075', 'Chettinadu Chicken Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00076', 'Chettinadu Fry - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00077', 'Chettinadu Fry - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00078', 'Chettinadu Fry - Nandu Vadai', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00079', 'Chettinadu Fry - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00080', 'Chettinadu Kari Varuval', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00081', 'Chettinadu Muttai Kulambu', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00082', 'Chicken Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00083', 'Chicken Burger', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00084', 'Chicken Burger - Double Patty', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00085', 'Chicken Cheese Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00086', 'Chicken Classic - Large', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00087', 'Chicken Classic - Medium', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00088', 'Chicken Classic - Regular', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00089', 'Chicken Club Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00090', 'Chicken Kalmi Kebab', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00091', 'Chicken Keema Dosa', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00092', 'Chicken Kola Urundai - 5 Pieces', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00093', 'Chicken Koththu Kari Dosa', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00094', 'Chicken Kurma', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00095', 'Chicken Lasagna', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00096', 'Chicken Lollypop - 5 Pieces', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00097', 'Chicken Makhani', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00098', 'Chicken Mushroom Pie', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00099', 'Chicken Nesamani', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00100', 'Chicken Nizam', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00101', 'Chicken Pallipalayam', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00102', 'Chicken Pasta - Red', 'CAT-PASTAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00103', 'Chicken Pasta - Red & White', 'CAT-PASTAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00104', 'Chicken Pasta - White', 'CAT-PASTAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00105', 'Chicken Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00106', 'Chicken Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00107', 'Chicken Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00108', 'Chicken Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00109', 'Chicken Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00110', 'Chicken Salt & Pepper', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00111', 'Chicken Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00112', 'Chicken Sheek Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00113', 'Chicken Sizzlers', 'CAT-SIZZLERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00114', 'Chicken Spring Roll', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00115', 'Chicken Sticks', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00116', 'Chicken Suicide Bombs', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00117', 'Chicken Supreme Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00118', 'Chicken Supreme Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00119', 'Chicken Supreme Pizza - Small', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00120', 'Chicken Tangri Kebab - 1 Piece', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00121', 'Chicken Tikka', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00122', 'Chicken Tikka Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00123', 'Chicken Tikka Dosa', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00124', 'Chicken Tikka Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00125', 'Chicken Tikka Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00126', 'Chilli - Babycorn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00127', 'Chilli - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00128', 'Chilli - Crab Podimas', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00129', 'Chilli - Egg', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00130', 'Chilli - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00131', 'Chilli - Gobi', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00132', 'Chilli - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00133', 'Chilli - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00134', 'Chilli - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00135', 'Chilli Cheese Toast', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00136', 'Chilli Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00137', 'Chilli Garlic Chicken Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00138', 'Chilli Garlic Potato', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00139', 'Chilli Mutton Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00140', 'Chinese Chopsey - Chicken', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00141', 'Chinese Chopsey - Veg', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00142', 'Chipotle Chilaquiles', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00143', 'Chipotle Mango Barbecue Chicken', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00144', 'Choco Chip Cookie Shake', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00145', 'Chocolate - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00146', 'Chocolate - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00147', 'Chocolate M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00148', 'Clear Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00149', 'Clear Soup - Veg', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00150', 'Coconut Oil - Farm fresh', 'CAT-SIDES', 'SUBCAT-SIDES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00151', 'Coconut Pancakes', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00152', 'Coffee', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00153', 'Coffee Brazillia - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00154', 'Coffee Brazillia - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00155', 'Coffee Brazillia M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00156', 'Cold Coffee', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00157', 'Coleslaw Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00158', 'Crab - Balls', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00159', 'Crab Lollypop', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00160', 'Crab Podimas', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00161', 'Cream of Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00162', 'Cream of Soup - Roasted Pumpkin', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00163', 'Cream of Soup - Tomato', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00164', 'Cream of Soup - Veg', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00165', 'Curd', 'CAT-SIDES', 'SUBCAT-SIDES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00166', 'Curd Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00167', 'Death by Chocolate', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00168', 'Devil''s Drink', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00169', 'Deviled Egg Prawn Dippers', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00170', 'Deviled Egg Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00171', 'Dhal Fry', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00172', 'Dhal Makhani', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00173', 'Dhal Palak', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00174', 'Dhal Tadka', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00175', 'Dirty Sandwich Sizzler - Chicken', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00176', 'Dirty Sandwich Sizzler - Veg', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00177', 'Double Patty - Chicken Burger', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00178', 'Double Patty - Veg Burger', 'CAT-BURGERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00179', 'Dragon Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00180', 'Drink the Pan', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00181', 'Drums of Heaven - 5 Pieces', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00182', 'Egg - Half Boil', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00183', 'Egg & Chicken Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00184', 'Egg Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00185', 'Egg Dosa', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00186', 'Egg Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00187', 'Egg Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00188', 'Egg Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00189', 'Extra Cheese', 'CAT-SIDES', 'SUBCAT-SIDES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00190', 'Fire Cooked - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00191', 'Fire Cooked - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00192', 'Fish Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00193', 'Fish Fingers', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00194', 'Fish Fry Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00195', 'Fish in Banana Leaf', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00196', 'Fish n Chips', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00197', 'French Fries', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00198', 'French Toast', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00199', 'Fried - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00200', 'Fried - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00201', 'Fried - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00202', 'Fried - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00203', 'Fried - Prawns', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00204', 'Fried Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00205', 'Fried Prawns', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00206', 'Fried Rice - Chicken', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00207', 'Fried Rice - Egg', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00208', 'Fried Rice - Mushroom', 'CAT-FRIED_RICE', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00209', 'Fried Rice - Paneer', 'CAT-FRIED_RICE', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00210', 'Fried Rice - Veg', 'CAT-FRIED_RICE', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00211', 'Fruit Bowl', 'CAT-DESSERTS', 'SUBCAT-FRUITS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00212', 'Fruit Bowl with Icecream', 'CAT-DESSERTS', 'SUBCAT-FRUITS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00213', 'Fruit Honey Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00214', 'Fruity Pebble', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00215', 'Fusion Burger - Barbecue Chicken', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00216', 'Fusion Burger - Chipotle Chicken', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00217', 'Fusion Burger - Chipotle Veg', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00218', 'Fusion Burger - Liquid Cheese Chicken', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00219', 'Fusion Burger - Shredded Chicken', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00220', 'Fusion Burger - Tandoori Chicken', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00221', 'Fusion Burger - Zesty Chicken', 'CAT-BURGERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00222', 'Fusion Burger - Zesty Veg', 'CAT-BURGERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00223', 'Garlic Bread', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00224', 'Ghee Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00225', 'Ginger Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00226', 'Ginger Tea', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00227', 'Golden Fried Babycorn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00228', 'Gramathu Mutton Kuzhambu', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00229', 'Green Apple Mojito', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00230', 'Green Peas Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00231', 'Green Peas Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00232', 'Green Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00233', 'Green Tea - Ginger, Lemon & Honey', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00234', 'Green Tea - Honey', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00235', 'Grilled Cheese Soup Dippers', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00236', 'Grilled Fish - Large', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00237', 'Grilled Fish - Small', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00238', 'Grilled Paneer Slabs', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00239', 'Grilled Pasta Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00240', 'Grilled Pineapple with BBQ Salsa', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00241', 'Grilled Prawns', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00242', 'Grilled Prawns with Garlic sauce', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00243', 'Grilled Tuscan Chicken', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00244', 'Gulab Jamoon', 'CAT-DESSERTS', 'SUBCAT-SWEETS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00245', 'Guntur Chicken Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00246', 'Hariyali Smoked Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00247', 'Hariyali Smoked Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00248', 'Hariyali Smoked Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00249', 'Hariyali Tikka - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00250', 'Hariyali Tikka - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00251', 'Hariyali Tikka - Gobi', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00252', 'Hariyali Tikka - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00253', 'Hariyali Tikka - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00254', 'Hariyali Tikka - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00255', 'Hawaiian Grilled Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00256', 'High on Sky', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00257', 'Home Style Chicken Curry', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00258', 'Hot n Sour Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00259', 'Hot n Sour Soup - Veg', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00260', 'Hot n Spicy Fish Toast', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00261', 'Hyderabadi Chicken Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00262', 'Ice Tea', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00263', 'Italian Cheesy Baked Chicken', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00264', 'Jeera Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00265', 'Kadai Chicken', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00266', 'Kadai Paneer', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00267', 'Kal Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00268', 'Kalakki', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00269', 'Karaikudi Chicken Dry', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00270', 'Karaikudi Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00271', 'Karaikudi thokku - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00272', 'Karaikudi thokku - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00273', 'Kashmiri Dum Aloo Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00274', 'Kernel Corn Vada', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00275', 'Kick Grass Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00276', 'Kulcha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00277', 'Lassi', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00278', 'Lemon Pepper Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00279', 'Lemon Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00280', 'Lemon Tea', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00281', 'Lime Juice', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00282', 'Lime Juice - S & S', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00283', 'Lime Juice - Salt', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00284', 'Lime Juice - Sweet', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00285', 'Lime Soda - S & S', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00286', 'Lime Soda - Salt', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00287', 'Lime Soda - Sweet', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00288', 'Lollypop 5 pcs - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00289', 'Lollypop 5 pcs - Corn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00290', 'Lollypop 5 pcs - Crab', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00291', 'Lollypop 5 pcs - Veg', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00292', 'Malai Chicken', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00293', 'Malai Kebab - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00294', 'Malai Kebab - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00295', 'Malai Kebab - Gobi', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00296', 'Malai Kebab - Mushroom Tikka', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00297', 'Malai Kebab - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00298', 'Malai Kebab - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00299', 'Manchow Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00300', 'Manchow Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00301', 'Manchow Soup - Veg', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00302', 'Manchurian - Babycorn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00303', 'Manchurian - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00304', 'Manchurian - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00305', 'Manchurian - Gobi', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00306', 'Manchurian - Gobi', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00307', 'Manchurian - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00308', 'Manchurian - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00309', 'Manchurian - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00310', 'Manchurian - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00311', 'Manchurian - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00312', 'Manchurian - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00313', 'Manchurian - Veg Balls', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00314', 'Mango - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00315', 'Mango - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00316', 'Mango Lassi', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00317', 'Mango M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00318', 'Mango Mousse', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00319', 'Mango Mule', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00320', 'Margherita Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00321', 'Margherita Pizza - Small', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00322', 'Margherita Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00323', 'Masala Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00324', 'Masala Fried Fish - Large', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00325', 'Masala Fried Fish - Medium', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00326', 'Masala Fried Fish - Small', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00327', 'Masala Omlette', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00328', 'Masala Papad', 'CAT-SIDES', 'SUBCAT-SIDES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00329', 'Masala Tea', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00330', 'Masala Uthappam', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00331', 'Matar - Mushroom', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00332', 'Matar - Paneer', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00333', 'Meen Podimas', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00334', 'Milk', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00335', 'Minced Mutton', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00336', 'Minestrone', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00337', 'Mini Lamb Satay Sticks', 'CAT-APPETIZERS', 'SUBCAT-BARBECUE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00338', 'Mint Lime Juice - S & S', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00339', 'Mint Lime Juice - Salt', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00340', 'Mint Lime Juice - Sweet', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00341', 'Mint Lime Soda - S & S', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00342', 'Mint Lime Soda - Salt', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00343', 'Mint Lime Soda - Sweet', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00344', 'Mint Mayo Chicken Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00345', 'Mint Mojito', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00346', 'Mixed Fried Rice - Non-Veg', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00347', 'Mixed Fried Rice - Veg', 'CAT-FRIED_RICE', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00348', 'Mixed Noodles - Non-Veg', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00349', 'Mixed Noodles - Veg', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00350', 'Mixed Veg Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00351', 'Mushroom Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00352', 'Mushroom Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00353', 'Mushroom Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00354', 'Mushroom Omlette', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00355', 'Mushroom Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00356', 'Mushroom Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00357', 'Mushroom Pizza - Small', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00358', 'Mushroom Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00359', 'Mushroom Roll', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00360', 'Muskmelon Juice', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00361', 'Mutton Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00362', 'Mutton Ghee Roast', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00363', 'Mutton Keema', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00364', 'Mutton Keema Dosa', 'CAT-DOSAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00365', 'Mutton Kola Urundai 5 pcs', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00366', 'Mutton Kudal Pepper Fry', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00367', 'Mutton Liver Fry', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00368', 'Mutton Pepper Fry', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00369', 'Mutton Peratal', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00370', 'Mutton Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00371', 'Mutton Raththa Poriyal', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00372', 'Mutton Sheek Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00373', 'Mutton Sukka', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00374', 'Naatu Kozhi Kulambu', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00375', 'Nasi Goreng Prawn Fried Rice', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00376', 'Nasi Goreng Prawn Noodles', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00377', 'Non-Veg Tandoori Platter', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00378', 'Noodle - Chicken Soup', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00379', 'Noodle - Veg Soup', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00380', 'Noodles - Chicken', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00381', 'Noodles - Egg', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00382', 'Noodles - Mushroom', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00383', 'Noodles - Paneer', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00384', 'Noodles - Veg', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00385', 'Nutella Hazelnut Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00386', 'Nutty Challenge', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00387', 'Oats Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00388', 'Onion Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00389', 'Onion Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00390', 'Onion Uthappam', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00391', 'Orange Chicken', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00392', 'Orange Juice', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00393', 'Organic Small Bee Honey - 1kg', 'CAT-SIDES', 'SUBCAT-SIDES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00394', 'Pallipalayam - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00395', 'Pallipalayam - Mutton', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00396', 'Pan Climax M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00397', 'Pan Lassi', 'CAT-BEVERAGES', 'SUBCAT-COLD', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00398', 'Paneer Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00399', 'Paneer Bread Roll', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00400', 'Paneer Butter Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00401', 'Paneer Frankie', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00402', 'Paneer Keema Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00403', 'Paneer Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00404', 'Paneer Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00405', 'Paneer Pizza - Small', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00406', 'Paneer Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00407', 'Paneer Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00408', 'Paneer Tikka Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00409', 'Paneer Tikka Roll', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00410', 'Peanut Butter Brownie Shake', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00411', 'Pepper Chicken Dry', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00412', 'Pepper Chicken Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00413', 'Pepper Fry - Babycorn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00414', 'Pepper Fry - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00415', 'Pepper Fry - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00416', 'Pepper Fry - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00417', 'Pepper Fry - Mutton', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00418', 'Pepper Fry - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00419', 'Peri Peri Chicken Kebab', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00420', 'Peri Peri Chicken Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00421', 'Peri Peri Chicken Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00422', 'Peri Peri Chicken Roll', 'CAT-ROLLS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00423', 'Peri Peri Fries', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00424', 'Pesto Pasta - Chicken', 'CAT-PASTAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00425', 'Pesto Pasta - Veg', 'CAT-PASTAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00426', 'Pineapple Juice', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00427', 'Pink Lips', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00428', 'Pink Pasta - Chicken', 'CAT-PASTAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00429', 'Pink Pasta - Veg', 'CAT-PASTAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00430', 'Pistanut - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00431', 'Pistanut - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00432', 'Pistanut M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00433', 'Pitchupotta Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00434', 'Plain Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00435', 'Plain Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00436', 'Plain Omlette', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00437', 'Plain Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00438', 'Plain Uthappam', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00439', 'Platter - Non-Veg', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00440', 'Podi Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00441', 'Pomfret Fish Fry', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00442', 'Popcorn Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00443', 'Prawn Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00444', 'Prawn Cocktail Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00445', 'Prawn Fry Masala', 'CAT-CURRIES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00446', 'Prawn Toast', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00447', 'Pulka', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00448', 'Rava Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00449', 'Red Diesel', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00450', 'Reshmi Kebab', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00451', 'Roasted Chicken Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00452', 'Roasted Chicken Slices', 'CAT-SNACK', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00453', 'Rumali Roti', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00454', 'Russian Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00455', 'Salt & Pepper - Babycorn', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00456', 'Salt & Pepper - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00457', 'Salt & Pepper - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00458', 'Salt & Pepper - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00459', 'Sambar Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00460', 'Schezwan Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00461', 'Schezwan Fried Rice - Chicken', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00462', 'Schezwan Fried Rice - Egg', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00463', 'Schezwan Fried Rice - Veg', 'CAT-FRIED_RICE', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00464', 'Schezwan Noodles - Chicken', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00465', 'Schezwan Noodles - Egg', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00466', 'Schezwan Noodles - Veg', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00467', 'Scrambled Egg', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00468', 'Seafood Lasagna', 'CAT-SNACK', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00469', 'Seafood Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00470', 'Seafood Pizza - Small', 'CAT-PIZZAS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00471', 'Seafood Sizzlers', 'CAT-SIZZLERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00472', 'Seasonal fruits', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00473', 'Set Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00474', 'Sheek Kebab - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00475', 'Sheek Kebab - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00476', 'Sheek Kebab - Mutton', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00477', 'Shorba - Chicken Soup', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00478', 'Shorba - Veg Soup', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00479', 'Shredded Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00480', 'Smoked - Chicken on the Flame', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00481', 'Smoked - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00482', 'Smoked - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00483', 'Spanish Omlette', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00484', 'Spicy Paprika Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00485', 'Strawberry - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00486', 'Strawberry - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00487', 'Strawberry M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00488', 'Stuffed Bell Peppers', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00489', 'Stuffed Kulcha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00490', 'Stuffed Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00491', 'Stuffed Paratha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00492', 'Sukka - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00493', 'Sukka - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00494', 'Sukka - Mutton', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00495', 'Sukka - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00496', 'Sundae of the day', 'CAT-DESSERTS', 'SUBCAT-PASTRY', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00497', 'Sunset Surprise', 'CAT-BEVERAGES', 'SUBCAT-MOJITOS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00498', 'Sweet of the day', 'CAT-DESSERTS', 'SUBCAT-SWEETS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00499', 'Sweetcorn Soup - Chicken', 'CAT-SOUPS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00500', 'Sweetcorn Soup - Veg', 'CAT-SOUPS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00501', 'Tandoori Chicken - Full', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00502', 'Tandoori Chicken - Half', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00503', 'Tandoori Grilled - Chicken Sandwich', 'CAT-SANDWICHES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00504', 'Tawa Chicken-Rice/Salad', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00505', 'Tawa Toasted Chicken - Rice/Salad', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00506', 'Tea', 'CAT-BEVERAGES', 'SUBCAT-HOT', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00507', 'Thai Basil Fried Rice - Chicken', 'CAT-FRIED_RICE', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00508', 'Thai Basil Fried Rice - Veg', 'CAT-FRIED_RICE', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00509', 'Thai Basil Noodles - Chicken', 'CAT-NOODLES', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00510', 'Thai Basil Noodles - Veg', 'CAT-NOODLES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00511', 'Thai Sizzlers', 'CAT-SIZZLERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00512', 'Thalluvandi Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00513', 'Thoothukudi Chicken Dry', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00514', 'Tikka - Chicken', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00515', 'Tikka - Fish', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00516', 'Tikka - Mushroom', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00517', 'Tikka - Paneer', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00518', 'Tikka - Prawn', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00519', 'Tikkis - 6 Pieces - Chicken', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00520', 'Tikkis - 6 Pieces - Paneer', 'CAT-KICK_GRASS_SPECIALS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00521', 'Tomato Rice', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00522', 'Tornado Potatoes', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00523', 'Tossed Salad', 'CAT-SIDES', 'SUBCAT-SALADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00524', 'Twisted Lamb Kebabs', 'CAT-APPETIZERS', 'SUBCAT-NON_VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00525', 'Vanilla - I/C - Regular', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00526', 'Vanilla - I/C - Single', 'CAT-DESSERTS', 'SUBCAT-ICECREAMS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00527', 'Vanilla M/S', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00528', 'Vanilla Wonders', 'CAT-BEVERAGES', 'SUBCAT-MILKSHAKES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00529', 'Veg  Biryani', 'CAT-MAIN_COURSE', 'SUBCAT-BIRYANIS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00530', 'Veg Achar', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00531', 'Veg Burger', 'CAT-BURGERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00532', 'Veg Cheese Balls', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00533', 'Veg Cheese Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00534', 'Veg Chettinadu Masala', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00535', 'Veg Club Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00536', 'Veg Falafel', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00537', 'Veg Gold Coin', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00538', 'Veg Kadai', 'CAT-CURRIES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00539', 'Veg Kari Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00540', 'Veg Keema Dosa', 'CAT-DOSAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00541', 'Veg Lasagna', 'CAT-SNACK', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00542', 'Veg Lollypop', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00543', 'Veg Pasta - Red', 'CAT-PASTAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00544', 'Veg Pasta - Red & White', 'CAT-PASTAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00545', 'Veg Pasta - White', 'CAT-PASTAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00546', 'Veg Pulao', 'CAT-MAIN_COURSE', 'SUBCAT-RICE_VARIETIES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00547', 'Veg Roll', 'CAT-ROLLS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00548', 'Veg Sandwich', 'CAT-SANDWICHES', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00549', 'Veg Sheek Kebab', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00550', 'Veg Sizzlers', 'CAT-SIZZLERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00551', 'Veg Spring Roll', 'CAT-APPETIZERS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00552', 'Veg Supreme Pizza - Large', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00553', 'Veg Supreme Pizza - Regular', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00554', 'Veg Supreme Pizza - Small', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00555', 'Veggie Classic - Large', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00556', 'Veggie Classic - Regular', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00557', 'Veggie Cloud 9 - Large', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00558', 'Veggie Cloud 9 - Regular', 'CAT-PIZZAS', 'SUBCAT-VEG', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00559', 'Water Bottle - 1ltr', 'CAT-SIDES', 'SUBCAT-SIDES', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00560', 'Watermelon Juice', 'CAT-BEVERAGES', 'SUBCAT-FRESH_JUICE', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00561', 'Wheat Kothu Parotta - Chicken', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00562', 'Wheat Kothu Parotta - Egg', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00563', 'Wheat Kothu Parotta - Paneer', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00564', 'Wheat Kothu Parotta - Veg', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');
INSERT INTO products (id, name, category_id, subcategory_id, business_id) VALUES ('PROD-00565', 'Wheat Paratha', 'CAT-MAIN_COURSE', 'SUBCAT-INDIAN_BREADS', 'BIZ-RES-0001');