INSERT INTO categories (id, name, business_id) VALUES ('CAT-APPETIZERS', 'Appetizers', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-CURRIES', 'Curries', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-NOODLES', 'Noodles', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-BEVERAGES', 'Beverages', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-DESSERTS', 'Desserts', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-SOUPS', 'Soups', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-SANDWICHES', 'Sandwiches', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-PIZZAS', 'Pizzas', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-MAIN_COURSE', 'Main Course', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-KICK_GRASS_SPECIALS', 'Kick Grass Specials', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-BURGERS', 'Burgers', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-DOSAS', 'Dosas', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-ROLLS', 'Rolls', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-PASTAS', 'Pastas', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-SIZZLERS', 'Sizzlers', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-SIDES', 'Sides', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-FRIED_RICE', 'Fried Rice', 'BIZ-RES-0001');
INSERT INTO categories (id, name, business_id) VALUES ('CAT-SNACK', 'Snack', 'BIZ-RES-0001');