UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = '65 - Babycorn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = '65 - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = '65 - Egg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = '65 - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = '65 - Gobi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = '65 - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = '65 - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = '65 - Prawn';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Aloo Capsicum';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Aloo Gobi Masala';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Aloo Jeera';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Aloo Matar';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Aloo Paneer Masala';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'American Chopsey - Chicken';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'American Chopsey - Veg';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Apple Juice';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Apple Pie';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Apple Pie with Icecream';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Appuchi Chicken';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Arabian Delight - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Arabian Delight - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Arabian Delight M/S';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Assorted Veg Platter';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Authentic Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Authentic Soup - Mutton';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Authentic Soup - Tomato';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Authentic Soup - Veg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Baked Vegetables';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'BBQ Chicken Grilled Sandwich';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'BBQ Chicken Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'BBQ Chicken Pizza - Regular';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'BBQ Prawns with Roast Chilli Salsa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Bhurji - Egg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Bhurji - Paneer';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Bindi Kadai';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Bindi Masala';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Black Coffee';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Black Tea';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Blackcurrent - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Blackcurrent - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Blackcurrent M/S';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Boiled Egg - 2 Pieces';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Bone Chicken Biryani';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Bread Butter Jam Toast';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Bread Omlette';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Aloo Kulcha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Aloo Paratha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Butter Kulcha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Butter Naan';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Butter Roti';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Garlic Naan';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Gobi Paratha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Kulcha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Naan';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Paneer Kulcha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Paneer Paratha';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Breads - Tandoori Roti';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Brownie';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Brownie Sizzlers';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Brownie with Icecream';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Bruschetta';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Butter Chicken Masala';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Buttermilk';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Butterscotch - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Butterscotch - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Butterscotch M/S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Caramel Blast';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'Caribbean Chicken';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Cashew Pulao';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Channa Masala';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Chapati';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Cheese Garlic Bread';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Chef''s Delight Atta Roll - Chicken';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-VEG' WHERE name = 'Chef''s Delight Atta Roll - Veg';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Chettinadu Chicken Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chettinadu Fry - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chettinadu Fry - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chettinadu Fry - Nandu Vadai';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chettinadu Fry - Prawn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chettinadu Kari Varuval';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Chettinadu Muttai Kulambu';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Chicken Biryani';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Chicken Burger';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Chicken Burger - Double Patty';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Chicken Cheese Sandwich';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Classic - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Classic - Medium';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Classic - Regular';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Chicken Club Sandwich';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Kalmi Kebab';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Keema Dosa';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Kola Urundai - 5 Pieces';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Koththu Kari Dosa';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Kurma';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Lasagna';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Lollypop - 5 Pieces';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Chicken Makhani';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Mushroom Pie';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Nesamani';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Nizam';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Pallipalayam';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-NON_VEG' WHERE name = 'Chicken Pasta - Red';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-NON_VEG' WHERE name = 'Chicken Pasta - Red & White';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-NON_VEG' WHERE name = 'Chicken Pasta - White';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Pizza - Regular';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Pizza - Regular';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Chicken Pulao';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Chicken Roll';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Salt & Pepper';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Chicken Sandwich';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Chicken Sheek Roll';
UPDATE products SET category_id = 'CAT-SIZZLERS', subcategory_id = 'SUBCAT-SIZZLERS-NON_VEG' WHERE name = 'Chicken Sizzlers';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Spring Roll';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Sticks';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Suicide Bombs';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Supreme Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Supreme Pizza - Regular';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Chicken Supreme Pizza - Small';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Tangri Kebab - 1 Piece';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chicken Tikka';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Chicken Tikka Biryani';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Chicken Tikka Dosa';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Chicken Tikka Masala';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Chicken Tikka Roll';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Chilli - Babycorn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chilli - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chilli - Crab Podimas';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chilli - Egg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chilli - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Chilli - Gobi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Chilli - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Chilli - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chilli - Prawn';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Chilli Cheese Toast';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Chilli Chicken';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Chilli Garlic Chicken Roll';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Chilli Garlic Potato';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Chilli Mutton Roll';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Chinese Chopsey - Chicken';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Chinese Chopsey - Veg';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Chipotle Chilaquiles';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'Chipotle Mango Barbecue Chicken';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Choco Chip Cookie Shake';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Chocolate - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Chocolate - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Chocolate M/S';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Clear Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Clear Soup - Veg';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SIDES' WHERE name = 'Coconut Oil - Farm fresh';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-VEG' WHERE name = 'Coconut Pancakes';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Coffee';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Coffee Brazillia - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Coffee Brazillia - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Coffee Brazillia M/S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Cold Coffee';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Coleslaw Salad';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Crab - Balls';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Crab Lollypop';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Crab Podimas';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Cream of Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Cream of Soup - Roasted Pumpkin';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Cream of Soup - Tomato';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Cream of Soup - Veg';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SIDES' WHERE name = 'Curd';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Curd Rice';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Death by Chocolate';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Devil''s Drink';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Deviled Egg Prawn Dippers';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Deviled Egg Salad';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Dhal Fry';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Dhal Makhani';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Dhal Palak';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Dhal Tadka';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Dirty Sandwich Sizzler - Chicken';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Dirty Sandwich Sizzler - Veg';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Double Patty - Chicken Burger';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-VEG' WHERE name = 'Double Patty - Veg Burger';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Dragon Chicken';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'Drink the Pan';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Drums of Heaven - 5 Pieces';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Egg - Half Boil';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Egg & Chicken Roll';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Egg Biryani';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Egg Dosa';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Egg Masala';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Egg Roll';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Egg Sandwich';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SIDES' WHERE name = 'Extra Cheese';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fire Cooked - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fire Cooked - Prawn';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Fish Biryani';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fish Fingers';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Fish Fry Masala';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Fish in Banana Leaf';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Fish n Chips';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'French Fries';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'French Toast';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fried - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fried - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Fried - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Fried - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fried - Prawns';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fried Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Fried Prawns';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Fried Rice - Chicken';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Fried Rice - Egg';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-VEG' WHERE name = 'Fried Rice - Mushroom';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-VEG' WHERE name = 'Fried Rice - Paneer';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-VEG' WHERE name = 'Fried Rice - Veg';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-FRUITS' WHERE name = 'Fruit Bowl';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-FRUITS' WHERE name = 'Fruit Bowl with Icecream';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Fruit Honey Sandwich';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Fruity Pebble';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Barbecue Chicken';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Chipotle Chicken';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Chipotle Veg';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Liquid Cheese Chicken';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Shredded Chicken';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Tandoori Chicken';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-NON_VEG' WHERE name = 'Fusion Burger - Zesty Chicken';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-VEG' WHERE name = 'Fusion Burger - Zesty Veg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Garlic Bread';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Ghee Rice';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Ginger Chicken';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Ginger Tea';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Golden Fried Babycorn';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Gramathu Mutton Kuzhambu';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'Green Apple Mojito';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Green Peas Masala';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Green Peas Pulao';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Green Salad';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Green Tea - Ginger, Lemon & Honey';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Green Tea - Honey';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-VEG' WHERE name = 'Grilled Cheese Soup Dippers';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Grilled Fish - Large';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Grilled Fish - Small';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Grilled Paneer Slabs';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Grilled Pasta Sandwich';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'Grilled Pineapple with BBQ Salsa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Grilled Prawns';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'Grilled Prawns with Garlic sauce';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'Grilled Tuscan Chicken';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-SWEETS' WHERE name = 'Gulab Jamoon';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Guntur Chicken Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Hariyali Smoked Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Hariyali Smoked Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Hariyali Smoked Prawn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Hariyali Tikka - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Hariyali Tikka - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Hariyali Tikka - Gobi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Hariyali Tikka - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Hariyali Tikka - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Hariyali Tikka - Prawn';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Hawaiian Grilled Sandwich';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'High on Sky';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Home Style Chicken Curry';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Hot n Sour Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Hot n Sour Soup - Veg';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Hot n Spicy Fish Toast';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Hyderabadi Chicken Masala';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Ice Tea';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Italian Cheesy Baked Chicken';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Jeera Rice';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Kadai Chicken';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Kadai Paneer';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Kal Dosa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Kalakki';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Karaikudi Chicken Dry';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Karaikudi Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Karaikudi thokku - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Karaikudi thokku - Prawn';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Kashmiri Dum Aloo Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Kernel Corn Vada';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Kick Grass Sandwich';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Kulcha';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Lassi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Lemon Pepper Chicken';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Lemon Rice';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Lemon Tea';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Lime Juice';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Lime Juice - S & S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Lime Juice - Salt';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Lime Juice - Sweet';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Lime Soda - S & S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Lime Soda - Salt';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Lime Soda - Sweet';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Lollypop 5 pcs - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Lollypop 5 pcs - Corn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Lollypop 5 pcs - Crab';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Lollypop 5 pcs - Veg';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Malai Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Malai Kebab - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Malai Kebab - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Malai Kebab - Gobi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Malai Kebab - Mushroom Tikka';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Malai Kebab - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Malai Kebab - Prawn';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Manchow Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Manchow Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Manchow Soup - Veg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Babycorn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Manchurian - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Manchurian - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Gobi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Gobi';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Manchurian - Prawn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Manchurian - Prawn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Manchurian - Veg Balls';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Mango - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Mango - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Mango Lassi';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Mango M/S';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Mango Mousse';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'Mango Mule';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Margherita Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Margherita Pizza - Small';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Margherita Sandwich';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Masala Dosa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Masala Fried Fish - Large';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Masala Fried Fish - Medium';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Masala Fried Fish - Small';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Masala Omlette';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SIDES' WHERE name = 'Masala Papad';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Masala Tea';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Masala Uthappam';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Matar - Mushroom';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Matar - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Meen Podimas';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Milk';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Minced Mutton';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Minestrone';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-BARBECUE' WHERE name = 'Mini Lamb Satay Sticks';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Mint Lime Juice - S & S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Mint Lime Juice - Salt';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Mint Lime Juice - Sweet';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Mint Lime Soda - S & S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Mint Lime Soda - Salt';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Mint Lime Soda - Sweet';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Mint Mayo Chicken Roll';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'Mint Mojito';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Mixed Fried Rice - Non-Veg';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-VEG' WHERE name = 'Mixed Fried Rice - Veg';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Mixed Noodles - Non-Veg';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Mixed Noodles - Veg';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Mixed Veg Masala';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Mushroom Biryani';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Mushroom Dosa';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Mushroom Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mushroom Omlette';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Mushroom Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Mushroom Pizza - Regular';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Mushroom Pizza - Small';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Mushroom Pulao';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Mushroom Roll';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Muskmelon Juice';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Mutton Biryani';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Ghee Roast';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Keema';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-NON_VEG' WHERE name = 'Mutton Keema Dosa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Kola Urundai 5 pcs';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Kudal Pepper Fry';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Liver Fry';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Pepper Fry';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Peratal';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Mutton Pulao';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Raththa Poriyal';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Mutton Sheek Roll';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Mutton Sukka';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Naatu Kozhi Kulambu';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Nasi Goreng Prawn Fried Rice';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Nasi Goreng Prawn Noodles';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Non-Veg Tandoori Platter';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Noodle - Chicken Soup';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Noodle - Veg Soup';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Noodles - Chicken';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Noodles - Egg';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Noodles - Mushroom';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Noodles - Paneer';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Noodles - Veg';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Nutella Hazelnut Sandwich';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Nutty Challenge';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Oats Chicken';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Onion Dosa';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Onion Salad';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Onion Uthappam';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Orange Chicken';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Orange Juice';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SIDES' WHERE name = 'Organic Small Bee Honey - 1kg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pallipalayam - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pallipalayam - Mutton';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Pan Climax M/S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-COLD' WHERE name = 'Pan Lassi';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Paneer Biryani';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Paneer Bread Roll';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Paneer Butter Masala';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Paneer Frankie';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Paneer Keema Dosa';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Paneer Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Paneer Pizza - Regular';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Paneer Pizza - Small';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Paneer Pulao';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Paneer Sandwich';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Paneer Tikka Masala';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Paneer Tikka Roll';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Peanut Butter Brownie Shake';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pepper Chicken Dry';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Pepper Chicken Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Pepper Fry - Babycorn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pepper Fry - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pepper Fry - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Pepper Fry - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pepper Fry - Mutton';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pepper Fry - Prawn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Peri Peri Chicken Kebab';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Peri Peri Chicken Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Peri Peri Chicken Pizza - Regular';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-NON_VEG' WHERE name = 'Peri Peri Chicken Roll';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Peri Peri Fries';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-NON_VEG' WHERE name = 'Pesto Pasta - Chicken';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-VEG' WHERE name = 'Pesto Pasta - Veg';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Pineapple Juice';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Pink Lips';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-NON_VEG' WHERE name = 'Pink Pasta - Chicken';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-VEG' WHERE name = 'Pink Pasta - Veg';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Pistanut - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Pistanut - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Pistanut M/S';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Pitchupotta Chicken';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Plain Biryani';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Plain Dosa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Plain Omlette';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Plain Rice';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Plain Uthappam';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Platter - Non-Veg';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Podi Dosa';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Pomfret Fish Fry';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Popcorn Chicken';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Prawn Biryani';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Prawn Cocktail Salad';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-NON_VEG' WHERE name = 'Prawn Fry Masala';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Prawn Toast';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Pulka';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Rava Dosa';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'Red Diesel';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Reshmi Kebab';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Roasted Chicken Salad';
UPDATE products SET category_id = 'CAT-SNACK', subcategory_id = 'SUBCAT-SNACK-NON_VEG' WHERE name = 'Roasted Chicken Slices';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Rumali Roti';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Russian Salad';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Salt & Pepper - Babycorn';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Salt & Pepper - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Salt & Pepper - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Salt & Pepper - Prawn';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Sambar Rice';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Schezwan Chicken';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Schezwan Fried Rice - Chicken';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Schezwan Fried Rice - Egg';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-VEG' WHERE name = 'Schezwan Fried Rice - Veg';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Schezwan Noodles - Chicken';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Schezwan Noodles - Egg';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Schezwan Noodles - Veg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Scrambled Egg';
UPDATE products SET category_id = 'CAT-SNACK', subcategory_id = 'SUBCAT-SNACK-NON_VEG' WHERE name = 'Seafood Lasagna';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Seafood Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-NON_VEG' WHERE name = 'Seafood Pizza - Small';
UPDATE products SET category_id = 'CAT-SIZZLERS', subcategory_id = 'SUBCAT-SIZZLERS-NON_VEG' WHERE name = 'Seafood Sizzlers';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Seasonal fruits';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Set Dosa';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sheek Kebab - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sheek Kebab - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sheek Kebab - Mutton';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Shorba - Chicken Soup';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Shorba - Veg Soup';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Shredded Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Smoked - Chicken on the Flame';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Smoked - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Smoked - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Spanish Omlette';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Spicy Paprika Sandwich';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Strawberry - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Strawberry - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Strawberry M/S';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Stuffed Bell Peppers';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Stuffed Kulcha';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Stuffed Mushroom';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Stuffed Paratha';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sukka - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sukka - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sukka - Mutton';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Sukka - Prawn';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-PASTRY' WHERE name = 'Sundae of the day';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MOJITOS' WHERE name = 'Sunset Surprise';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-SWEETS' WHERE name = 'Sweet of the day';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-NON_VEG' WHERE name = 'Sweetcorn Soup - Chicken';
UPDATE products SET category_id = 'CAT-SOUPS', subcategory_id = 'SUBCAT-SOUPS-VEG' WHERE name = 'Sweetcorn Soup - Veg';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Tandoori Chicken - Full';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Tandoori Chicken - Half';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-NON_VEG' WHERE name = 'Tandoori Grilled - Chicken Sandwich';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Tawa Chicken-Rice/Salad';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Tawa Toasted Chicken - Rice/Salad';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-HOT' WHERE name = 'Tea';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-NON_VEG' WHERE name = 'Thai Basil Fried Rice - Chicken';
UPDATE products SET category_id = 'CAT-FRIED_RICE', subcategory_id = 'SUBCAT-FRIED_RICE-VEG' WHERE name = 'Thai Basil Fried Rice - Veg';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-NON_VEG' WHERE name = 'Thai Basil Noodles - Chicken';
UPDATE products SET category_id = 'CAT-NOODLES', subcategory_id = 'SUBCAT-NOODLES-VEG' WHERE name = 'Thai Basil Noodles - Veg';
UPDATE products SET category_id = 'CAT-SIZZLERS', subcategory_id = 'SUBCAT-SIZZLERS-NON_VEG' WHERE name = 'Thai Sizzlers';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Thalluvandi Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Thoothukudi Chicken Dry';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Tikka - Chicken';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Tikka - Fish';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Tikka - Mushroom';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Tikka - Paneer';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Tikka - Prawn';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-NON_VEG' WHERE name = 'Tikkis - 6 Pieces - Chicken';
UPDATE products SET category_id = 'CAT-KICK_GRASS_SPECIALS', subcategory_id = 'SUBCAT-KICK_GRASS_SPECIALS-VEG' WHERE name = 'Tikkis - 6 Pieces - Paneer';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Tomato Rice';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Tornado Potatoes';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SALADS' WHERE name = 'Tossed Salad';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-NON_VEG' WHERE name = 'Twisted Lamb Kebabs';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Vanilla - I/C - Regular';
UPDATE products SET category_id = 'CAT-DESSERTS', subcategory_id = 'SUBCAT-DESSERTS-ICECREAMS' WHERE name = 'Vanilla - I/C - Single';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Vanilla M/S';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-MILKSHAKES' WHERE name = 'Vanilla Wonders';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-BIRYANIS' WHERE name = 'Veg  Biryani';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Veg Achar';
UPDATE products SET category_id = 'CAT-BURGERS', subcategory_id = 'SUBCAT-BURGERS-VEG' WHERE name = 'Veg Burger';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Veg Cheese Balls';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Veg Cheese Sandwich';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Veg Chettinadu Masala';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Veg Club Sandwich';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Veg Falafel';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Veg Gold Coin';
UPDATE products SET category_id = 'CAT-CURRIES', subcategory_id = 'SUBCAT-CURRIES-VEG' WHERE name = 'Veg Kadai';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Veg Kari Dosa';
UPDATE products SET category_id = 'CAT-DOSAS', subcategory_id = 'SUBCAT-DOSAS-VEG' WHERE name = 'Veg Keema Dosa';
UPDATE products SET category_id = 'CAT-SNACK', subcategory_id = 'SUBCAT-SNACK-VEG' WHERE name = 'Veg Lasagna';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Veg Lollypop';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-VEG' WHERE name = 'Veg Pasta - Red';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-VEG' WHERE name = 'Veg Pasta - Red & White';
UPDATE products SET category_id = 'CAT-PASTAS', subcategory_id = 'SUBCAT-PASTAS-VEG' WHERE name = 'Veg Pasta - White';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-RICE_VARIETIES' WHERE name = 'Veg Pulao';
UPDATE products SET category_id = 'CAT-ROLLS', subcategory_id = 'SUBCAT-ROLLS-VEG' WHERE name = 'Veg Roll';
UPDATE products SET category_id = 'CAT-SANDWICHES', subcategory_id = 'SUBCAT-SANDWICHES-VEG' WHERE name = 'Veg Sandwich';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Veg Sheek Kebab';
UPDATE products SET category_id = 'CAT-SIZZLERS', subcategory_id = 'SUBCAT-SIZZLERS-VEG' WHERE name = 'Veg Sizzlers';
UPDATE products SET category_id = 'CAT-APPETIZERS', subcategory_id = 'SUBCAT-APPETIZERS-VEG' WHERE name = 'Veg Spring Roll';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veg Supreme Pizza - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veg Supreme Pizza - Regular';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veg Supreme Pizza - Small';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veggie Classic - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veggie Classic - Regular';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veggie Cloud 9 - Large';
UPDATE products SET category_id = 'CAT-PIZZAS', subcategory_id = 'SUBCAT-PIZZAS-VEG' WHERE name = 'Veggie Cloud 9 - Regular';
UPDATE products SET category_id = 'CAT-SIDES', subcategory_id = 'SUBCAT-SIDES-SIDES' WHERE name = 'Water Bottle - 1ltr';
UPDATE products SET category_id = 'CAT-BEVERAGES', subcategory_id = 'SUBCAT-BEVERAGES-FRESH_JUICE' WHERE name = 'Watermelon Juice';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Wheat Kothu Parotta - Chicken';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Wheat Kothu Parotta - Egg';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Wheat Kothu Parotta - Paneer';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Wheat Kothu Parotta - Veg';
UPDATE products SET category_id = 'CAT-MAIN_COURSE', subcategory_id = 'SUBCAT-MAIN_COURSE-INDIAN_BREADS' WHERE name = 'Wheat Paratha';